name: 'release-jira-fix-version'
description: 'Sets the release of a Jira version to true when passed in a version id'
author: 'Jim Yang'
inputs:
  email:
    required: true
    description: Email address associated with api token
  api-token:
    required: true
    description: Jira API token
  subdomain:
    required: true
    description: '{subdomain}.atlassian.net'
  version-id:
    required: true
    description: The id of the unreleased version
runs:
  using: 'node12'
  main: 'dist/index.js'
